title: AI Stability Framework
description: "Anti-hallucination middleware for AI chat platforms."
remote_theme: just-the-docs/just-the-docs

url: "https://leonardrojas.com"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

logo: "/assets/images/logo.png"
search_enabled: false
nav_sort: order
color_scheme: custom

footer_content: "© 2025-2026 Leonard Rojas. All rights reserved."

kramdown:
  input: kramdown
  syntax_highlighter_opts:
    block:
      line_numbers: false
