title: AI Stability Framework™
description: "Anti-hallucination middleware for AI chat platforms."

url: "https://leonardrojas.com"
baseurl: ""

exclude:
  - mistral-instruct
  - temp
  - Gemfile
  - Gemfile.lock
  - "*.bat"
  - git-web-fix.txt
  - HTML_editing_refs.md
  - PROD_index.md

plugins:
  - jekyll-seo-tag

logo: "/assets/images/logo.png"
footer_content: "© 2025-2026 Leonard Rojas. All rights reserved. AI Stability Framework wordmark and logo are trademarks of Leonard Rojas (USPTO Serial Nos. 99664948 and 99749758, registration pending). Contact: AISF at LeonardRojas dot com"

kramdown:
  input: kramdown
  syntax_highlighter_opts:
    block:
      line_numbers: false

defaults:
  - scope:
      path: ""
    values:
      layout: default
